# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        property:
            persistence:
                driver: orm
                model: App\Entity\Gestapp\Property
                provider: ~
                finder: ~
            properties:
                name:
                    type: text
                city:
                    type: text
                zipcode:
                    type: text
                refmandat:
                    type: integer
                isNomandat:
                    type: boolean
                isArchived:
                    type: boolean
                price:
                    type: integer
                rubric:
                    type: object
                    properties:
                        id: ~
                refEmployed:
                    type: object
                    properties:
                        id: ~
        customer:
            persistence:
                driver: orm
                model: App\Entity\Gestapp\Customer
                provider: ~
                finder: ~
            properties:
                refCustomer:
                    type: text
                firstName:
                    type: text
                lastName:
                    type: text
                city:
                    type: text
                zipcode:
                    type: text
                typeClient:
                    type: text

