# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        property:
            persistence:
                driver: orm
                model: App\Entity\Gestapp\Property
                elastica_to_model_transformer:
                    ignore_missing: true
                listener:
                    enabled: true
                    defer: false   # false = update direct, true = différé
                    insert: true   # indexe à la création
                    update: true   # met à jour à la modification
                    delete: true   # supprime à la suppression
                provider: ~
                finder: ~
            properties:
                name:
                    type: text
                city:
                    type: text
                zipcode:
                    type: text
                refmandat:
                    type: integer
                isNomandat:
                    type: boolean
                isArchived:
                    type: boolean
                price:
                    type: integer
                rubric:
                    type: object
                    properties:
                        id: ~
                refEmployed:
                    type: object
                    properties:
                        id: ~
        customer:
            persistence:
                driver: orm
                model: App\Entity\Gestapp\Customer
                provider: ~
                finder: ~
                listener:
                    enabled: true
                    defer: false   # false = update direct, true = différé
                    insert: true   # indexe à la création
                    update: true   # met à jour à la modification
                    delete: true   # supprime à la suppression
            properties:
                firstName:
                    type: text
                    fields:
                        keyword:
                            type: keyword
                lastName:
                    type: text
                    fields:
                        keyword:
                            type: keyword
                slug:
                    type: text
                    fields:
                        keyword:
                            type: keyword