# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        property:
            persistence:
                driver: orm
                model: App\Entity\Gestapp\Property
                provider: ~
                finder: ~
            properties :
                name: ~
                refEmployed:
                    type: object
                    properties:
                        id:~
