# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    twig:
        mode: lazy
    filter_sets:
        lastproperty_card:
            quality: 150
            filters:
                thumbnail:
                    size: [ 414, 305 ]
                    mode: outbond
                watermark_image:
                    # path to the watermark file (prepended with "%kernel.project_dir%")
                    image: assets/styles/images/svg/watermark.png
                    # size of the water mark relative to the input image
                    size: 0.5
                    # set the position of the watermark
                    position: center
                background:
                    color: '#fff'
                    size: [414,400]
                    position: top
        oneproperty_image:
            quality: 150
            filters:
                thumbnail:
                    size: [ 516, 387 ]
                    mode: outbond
                        # use and setup the "watermark_image" filter
                watermark_image:
                    # path to the watermark file (prepended with "%kernel.project_dir%")
                    image: assets/styles/images/svg/watermark.png
                    # size of the water mark relative to the input image
                    size: 0.5
                    # set the position of the watermark
                    position: center
                auto_rotate: ~
        oneproperty_galery:
            quality: 150
            filters:
                auto_rotate: ~
                thumbnail:
                    size: [ 355, 225 ]
                watermark_image:
                    # path to the watermark file (prepended with "%kernel.project_dir%")
                    image: assets/styles/images/svg/watermark.png
                    # size of the water mark relative to the input image
                    size: 0.5
                    # set the position of the watermark
                    position: center
        ficheproperty_image:
            quality: 150
            filters:
                auto_rotate: ~
                thumbnail:
                    size: [ 508, 381 ]
                background:
                    color: '#ffffff'
                    size: [ 516, 387 ]
                    position: center
                watermark_image:
                    # path to the watermark file (prepended with "%kernel.project_dir%")
                    image: assets/styles/images/svg/watermark.png
                    # size of the water mark relative to the input image
                    size: 0.5
                    # set the position of the watermark
                    position: center
        card_actualites:
            quality: 150
            filters:
                thumbnail:
                    size: [ 330, 248 ]
                    mode: outbond
        noscollaborateurs_card:
            quality: 150
            filters:
                thumbnail:
                    size: [ 200, 150 ]
                    mode: outbond
                background:
                    color: '#ffffff'
                    size: [ 200, 200 ]
                    position: center
        oneproperty_galleryAdmin:
            quality: 150
            filters:
                thumbnail:
                    size: [ 313, 210 ]
                    mode: outbond
                watermark_image:
                    # path to the watermark file (prepended with "%kernel.project_dir%")
                    image: assets/styles/images/svg/watermark.png
                    # size of the watermark relative to the input image
                    size: 0.5
                    # set the position of the watermark
                    position: center
        vignette_employed:
            quality: 75
            filters:
                thumbnail:
                    size: [ 120, 120 ]
                    mode: outbond
