vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        logosite_front:
            uri_prefix: /images/application
            upload_destination: '%kernel.project_dir%/public/images/application'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        favicon_front:
            uri_prefix: /images/application
            upload_destination: '%kernel.project_dir%/public/images/application'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        avatar_image:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/public/images/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        property_image:
            uri_prefix: /images/property
            upload_destination: '%kernel.project_dir%/public/images/property'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        article_front:
            uri_prefix: /images/article
            upload_destination: '%kernel.project_dir%/public/images/article'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        galery_front:
            uri_prefix: /images/galery
            upload_destination: '%kernel.project_dir%/public/images/galery'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        vignette_employed:
            uri_prefix: /images/employed
            upload_destination: '%kernel.project_dir%/public/images/employed'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true