controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

authentication_token:
    path: /authentication_token
    methods: ['POST']

get_token:
    path: /api/get_token_numCollaborator
    methods: [ 'POST' ]
