# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    application_directory: '%kernel.project_dir%/public/images/application'
    avatars_directory: '%kernel.project_dir%/public/images/avatar'
    banners_directory: '%kernel.project_dir%/public/images/svg'
    articles_directory: '%kernel.project_dir%/public/images/article'
    articles_pdf_directory: '%kernel.project_dir%/public/pdf/articles'
    document_pdf_directory: '%kernel.project_dir%/public/doc/pdf'
    document_word_directory: '%kernel.project_dir%/public/doc/word'
    document_excel_directory: '%kernel.project_dir%/public/doc/excel'
    document_mp4_directory: '%kernel.project_dir%/public/doc/mp4'
    transaction_promise_directory: '%kernel.project_dir%/public/doc/transaction/promise'
    transaction_acte_directory: '%kernel.project_dir%/public/doc/transaction/acte'
    transaction_tracfin_directory: '%kernel.project_dir%/public/doc/transaction/tracfin'
    transaction_invoice_directory: '%kernel.project_dir%/public/doc/transaction/invoice'
    property_photo_directory: '%kernel.project_dir%/public/properties/'
    property_doc_directory: '%kernel.project_dir%/public/properties/'
    property_product_directory: '%kernel.project_dir%/public/images/product/'
    prescriber_ci_directory: '%kernel.project_dir%/public/doc/prescriber/ci/'
    customer_ci_directory: '%kernel.project_dir%/public/customer/'
    customer_kbis_directory: '%kernel.project_dir%/public/customer/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Controller\Admin\SearchController:
        tags:
            - controller.service_arguments
        public: true
        arguments:
            - '@knp_paginator'
            - '@fos_elastica.finder.property'
            - '@fos_elastica.finder.customer'

    App\Service\imageTransfertService:
        arguments:
            $targetDirectoryAvatar: '%kernel.project_dir%/public/employed/'
            $targetDirectoryCi: '%kernel.project_dir%/public/employed/'

    App\Service\ftptransfertService:
        arguments:
            $projectDir: '%kernel.project_dir%/public/'



    App\OpenApi\JwtDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: [ '@.inner' ]