# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    avatars_directory: '%kernel.project_dir%/public/images/avatar'
    banners_directory: '%kernel.project_dir%/public/images/svg'
    articles_pdf_directory: '%kernel.project_dir%/public/pdf/articles'
    pdf_directory: '%kernel.project_dir%/public/doc/pdf'
    word_directory: '%kernel.project_dir%/public/doc/word'
    excel_directory: '%kernel.project_dir%/public/doc/excel'
    mp4_directory: '%kernel.project_dir%/public/doc/mp4'
    transaction_promise_directory: '%kernel.project_dir%/public/doc/transaction/promise'
    transaction_acte_directory: '%kernel.project_dir%/public/doc/transaction/acte'
    transaction_tracfin_directory: '%kernel.project_dir%/public/doc/transaction/tracfin'
    property_photo_directory: '%kernel.project_dir%/public/properties/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\ftptransfertService:
        arguments:
            # SE LOGER
            $urlftpseloger: '%env(URL_FTP_SELOGER)%'
            $portftpseloger: '%env(PORT_FTP_SELOGER)%'
            $loginftpseloger: '%env(LOGIN_FTP_SELOGER)%'
            $passwordftpseloger: '%env(PASSWORD_FTP_SELOGER)%'
            # FIGARO
            $urlftpfigaro: '%env(URL_FTP_FIGARO)%'
            $portftpfigaro: '%env(PORT_FTP_FIGARO)%'
            $loginftpfigaro: '%env(LOGIN_FTP_FIGARO)%'
            $passwordftpfigaro: '%env(PASSWORD_FTP_FIGARO)%'
            # GREEN ACRES
            $urlftpga: '%env(URL_FTP_GA)%'
            $portftpga: '%env(PORT_FTP_GA)%'
            $loginftpga: '%env(LOGIN_FTP_GA)%'
            $passwordftpga: '%env(PASSWORD_FTP_GA)%'
            # VIZZIT
            $urlftpvi: '%env(URL_FTP_VI)%'
            $portftpvi: '%env(PORT_FTP_VI)%'
            $loginftpvi: '%env(LOGIN_FTP_VI)%'
            $passwordftpvi: '%env(PASSWORD_FTP_VI)%'

    App\OpenApi\JwtDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: [ '@.inner' ]